/**
 * GET /provision/:slug
 * Returns a plain-text RouterOS (.rsc) script that fully provisions a MikroTik router.
 * The slug format is: <tenantId>-<router-identity>
 * Script is fetched by the router via:
 *   /tool fetch mode=https url="https://.../provision/<slug>" dst-path=<slug>.rsc
 *   /import <slug>.rsc
 */
import { createFileRoute } from "@tanstack/react-router";
import { useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/provision/$slug")({
  component: ProvisionRoute,
});

function ProvisionRoute() {
  const { slug } = Route.useParams();

  useEffect(() => {
    (async () => {
      // slug = "<tenantId>-<identity-slug>"
      // Find the router by provisioning_slug
      const { data: router } = await (supabase as any)
        .from("routers")
        .select("id, tenant_id, name, services, bridge_port, subnet, provisioning_slug, api_username, api_password, ip_address")
        .eq("provisioning_slug", slug)
        .maybeSingle();

      if (!router) {
        document.body.innerText = "# ERROR: Router not found for slug: " + slug;
        return;
      }

      // Fetch tenant slug (company name slug) for portal URL
      const { data: tenant } = await (supabase as any)
        .from("tenants")
        .select("slug, name")
        .eq("id", router.tenant_id)
        .maybeSingle();

      const ispSlug = tenant?.slug ?? router.tenant_id;
      const portalBase = "https://smart-link-kenya.vercel.app";
      const portalLoginPage = `${portalBase}/portal?isp=${ispSlug}&mac=\$(mac)&ip=\$(ip)&url=\$(link-orig)&dst=\$(dst-ip)`;

      const services: string[] = router.services ?? ["pppoe"];
      const hasHotspot = services.includes("hotspot");
      const hasPppoe = services.includes("pppoe");
      const bridgePort = router.bridge_port ?? "ether2";
      const subnet = router.subnet ?? "172.31.0.0/16";
      const companySlug = ispSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
      const bridgeName = `${companySlug}-bridge`;

      // Parse subnet for gateway IP (first usable address)
      const [networkAddr, prefixLen] = subnet.split("/");
      const parts = networkAddr.split(".").map(Number);
      parts[3] = 1; // gateway = x.x.x.1
      const gatewayIp = `${parts.join(".")}/${prefixLen}`;

      const lines: string[] = [
        `# SmartLinkNet — MikroTik Provisioning Script`,
        `# Router: ${router.name}`,
        `# Tenant: ${tenant?.name ?? router.tenant_id}`,
        `# Generated: ${new Date().toISOString()}`,
        `# DO NOT EDIT — auto-generated by SmartLinkNet`,
        ``,
        `# ── 1. Bridge ──────────────────────────────────────────────`,
        `/interface bridge`,
        `add name=${bridgeName} comment="SmartLinkNet managed bridge"`,
        ``,
        `/interface bridge port`,
        `add bridge=${bridgeName} interface=${bridgePort}`,
        ``,
        `# ── 2. IP Address on bridge ────────────────────────────────`,
        `/ip address`,
        `add address=${gatewayIp} interface=${bridgeName} comment="SmartLinkNet gateway"`,
        ``,
        `# ── 3. DHCP Server ─────────────────────────────────────────`,
        `/ip pool`,
        `add name=${companySlug}-pool ranges=${parts.slice(0, 3).join(".")}.10-${parts.slice(0, 3).join(".")}.254`,
        ``,
        `/ip dhcp-server`,
        `add name=${companySlug}-dhcp interface=${bridgeName} address-pool=${companySlug}-pool lease-time=1h disabled=no`,
        ``,
        `/ip dhcp-server network`,
        `add address=${subnet} gateway=${parts.join(".")} dns-server=8.8.8.8,8.8.4.4`,
        ``,
        `# ── 4. NAT / Masquerade ────────────────────────────────────`,
        `/ip firewall nat`,
        `add chain=srcnat out-interface-list=WAN action=masquerade comment="SmartLinkNet NAT"`,
        ``,
      ];

      if (hasHotspot) {
        lines.push(
          `# ── 5. Hotspot ─────────────────────────────────────────────`,
          `/ip hotspot profile`,
          `add name=${companySlug}-profile \\`,
          `  login-by=http-pap \\`,
          `  html-directory=hotspot \\`,
          `  http-cookie-lifetime=1d \\`,
          `  login-page="${portalLoginPage}"`,
          ``,
          `/ip hotspot`,
          `add name=${companySlug}-hotspot interface=${bridgeName} address-pool=${companySlug}-pool profile=${companySlug}-profile disabled=no`,
          ``,
          `# Walled Garden — allow portal + payment domains before login`,
          `/ip hotspot walled-garden`,
          `add dst-host=smart-link-kenya.vercel.app comment="SmartLinkNet portal"`,
          `add dst-host=*.vercel.app comment="Vercel CDN"`,
          `add dst-host=tghaarhofriakwgvqmpm.supabase.co comment="Supabase API"`,
          `add dst-host=*.supabase.co comment="Supabase CDN"`,
          `add dst-host=safaricom.com comment="M-Pesa"`,
          `add dst-host=*.safaricom.com comment="M-Pesa"`,
          `add dst-host=mpesa.safaricom.co.ke comment="M-Pesa STK"`,
          ``,
          `/ip hotspot walled-garden ip`,
          `add dst-address=0.0.0.0/0 protocol=tcp dst-port=443 comment="Allow HTTPS for portal"`,
          ``,
        );
      }

      if (hasPppoe) {
        lines.push(
          `# ── 6. PPPoE Server ────────────────────────────────────────`,
          `/interface pppoe-server server`,
          `add name=${companySlug}-pppoe interface=${bridgeName} default-profile=default disabled=no`,
          ``,
        );
      }

      lines.push(
        `# ── 7. DNS ─────────────────────────────────────────────────`,
        `/ip dns`,
        `set allow-remote-requests=yes servers=8.8.8.8,8.8.4.4`,
        ``,
        `# ── 8. RADIUS Accounting (sends session data to SmartLinkNet) ──`,
        `# NOTE: SmartLinkNet uses HTTP accounting via radius-accounting edge function.`,
        `# MikroTik sends accounting via RADIUS to the Supabase edge function endpoint.`,
        `# The secret below is your provisioning slug — keep it safe.`,
        `/radius`,
        `add service=hotspot,ppp address=tghaarhofriakwgvqmpm.supabase.co secret=${slug} authentication-port=1812 accounting-port=1813 timeout=3000ms comment="SmartLinkNet AAA"`,
        ``,
        ...(hasHotspot ? [
          `/ip hotspot profile`,
          `set [find name=${companySlug}-profile] use-radius=yes accounting=yes`,
          ``,
        ] : []),
        ...(hasPppoe ? [
          `/ppp profile`,
          `set [find name=default] use-radius=yes`,
          ``,
        ] : []),
        `# ── 9. Report back to SmartLinkNet ─────────────────────────`,
        `/system scheduler`,
        `add name=smartlinknet-heartbeat interval=5m on-event=":do { /tool fetch mode=https url=\\"${portalBase}/api/heartbeat?router=${slug}\\" keep-result=no } on-error={}" comment="SmartLinkNet heartbeat"`,
        ``,
        `# ── Done ────────────────────────────────────────────────────`,
        `:log info "SmartLinkNet provisioning complete for ${router.name}"`,
      );

      const script = lines.join("\n");

      // Serve as plain text by replacing the entire page
      document.open("text/plain");
      document.write(script);
      document.close();
    })();
  }, [slug]);

  return (
    <pre style={{ fontFamily: "monospace", fontSize: 13, padding: 16, whiteSpace: "pre-wrap" }}>
      Loading provisioning script for {slug}…
    </pre>
  );
}
