import "./lib/error-capture";

import { consumeLastCapturedError } from "./lib/error-capture";
import { renderErrorPage } from "./lib/error-page";
import { supabaseAdmin } from "./integrations/supabase/client.server";

type ServerEntry = {
  fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> | Response;
};

let serverEntryPromise: Promise<ServerEntry> | undefined;

function normalizeProvisionSlug(slug: string) {
  return slug.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/(^-|-$)/g, "") || "smartlinknet";
}

function getRouterIdentityFromSlug(slug: string) {
  const safeSlug = normalizeProvisionSlug(slug);
  return safeSlug.split("-").filter(Boolean).pop() || "MikroTik";
}

function parseProvisioningSlug(slug: string) {
  const safeSlug = normalizeProvisionSlug(slug);
  const uuidMatch = safeSlug.match(/^([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})-(.+)$/i);
  if (uuidMatch) {
    return { tenantId: uuidMatch[1], identity: uuidMatch[2] };
  }

  const parts = safeSlug.split("-").filter(Boolean);
  return { tenantId: null, identity: parts.pop() || "MikroTik" };
}

async function getRouterProvisionRecord(slug: string) {
  const safeSlug = normalizeProvisionSlug(slug);
  const { data, error } = await supabaseAdmin
    .from("routers")
    .select("id, services, bridge_port, subnet, provisioning_slug, provisioning_identity")
    .eq("provisioning_slug", safeSlug)
    .maybeSingle();

  if (!error && data) return data;

  const parsed = parseProvisioningSlug(safeSlug);
  if (parsed.tenantId && parsed.identity) {
    const { data: fallbackData, error: fallbackError } = await supabaseAdmin
      .from("routers")
      .select("id, services, bridge_port, subnet, provisioning_slug, provisioning_identity")
      .eq("tenant_id", parsed.tenantId)
      .ilike("name", `%${parsed.identity}%`)
      .order("created_at", { ascending: false })
      .limit(1);

    if (!fallbackError && fallbackData?.[0]) return fallbackData[0];
  }

  return null;
}

async function markRouterOnline(slug: string, request: Request) {
  try {
    const routerName = new URL(request.url).searchParams.get("router")?.trim() || getRouterIdentityFromSlug(slug);
    const record = await getRouterProvisionRecord(slug);
    const routerId = (record as { id?: string } | null | undefined)?.id;

    if (!routerId) {
      const { data, error } = await supabaseAdmin
        .from("routers")
        .select("id")
        .ilike("name", routerName)
        .limit(1);

      if (error || !data?.[0]?.id) return;
      await supabaseAdmin
        .from("routers")
        .update({
          status: "online",
          last_seen: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          ip_address: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null,
        } as any)
        .eq("id", data[0].id);
      return;
    }

    const forwardedFor = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim();
    await supabaseAdmin
      .from("routers")
      .update({
        status: "online",
        last_seen: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        ip_address: forwardedFor ?? null,
      } as any)
      .eq("id", routerId);
  } catch (error) {
    console.error("Failed to mark router online", error);
  }
}

async function buildProvisionScript(slug: string, origin: string) {
  const safeSlug = normalizeProvisionSlug(slug);
  const identity = getRouterIdentityFromSlug(slug);
  const bridgeName = "smartlinknet-automatic";
  const record = await getRouterProvisionRecord(safeSlug);
  const services = ((record?.services as string[] | undefined) ?? []).filter(Boolean);
  const bridgePort = typeof record?.bridge_port === "string" && record.bridge_port ? record.bridge_port : "ether2";
  const subnet = typeof record?.subnet === "string" && record.subnet ? record.subnet : "172.31.0.0/16";
  const notifyUrl = `${origin}/provision/notify/${safeSlug}?router=${encodeURIComponent(identity)}`;
  const [networkAddress, prefixLength] = subnet.split("/");
  const gateway = networkAddress ? networkAddress.replace(/\.0$/, ".1") : "172.31.0.1";
  const poolRange = networkAddress ? `${networkAddress.replace(/\.0$/, ".2")}-${networkAddress.replace(/\.0$/, ".254")}` : "172.31.0.2-172.31.0.254";
  const serviceSummary = services.length ? services.join(", ") : "none";

  return [
    "# Generated by SmartLinkNet",
    `# Router identity: ${identity}`,
    `# Enabled services: ${serviceSummary}`,
    `/system identity set name=\"${identity}\"`,
    `:local bridgeName \"${bridgeName}\"`,
    `:if ([:len [/interface bridge find name=\$bridgeName]] = 0) do={/interface bridge add name=\$bridgeName comment=\"SmartLinkNet auto-provisioned\"}`,
    `:if ([:len [/interface bridge port find interface=${bridgePort}]] = 0) do={/interface bridge port add bridge=\$bridgeName interface=${bridgePort}}`,
    `:if ([:len [/ip address find interface=\$bridgeName]] = 0) do={/ip address add address=${networkAddress}/${prefixLength ?? "16"} interface=\$bridgeName comment=\"SmartLinkNet default subnet\"}`,
    `:if ([:len [/ip pool find name=\$bridgeName]] = 0) do={/ip pool add name=\$bridgeName ranges=${poolRange}}`,
    `:if ([:len [/ip dhcp-server find name=\$bridgeName]] = 0) do={/ip dhcp-server add name=\$bridgeName interface=\$bridgeName address-pool=\$bridgeName lease-time=12h}`,
    `:if ([:len [/ip dhcp-server network find where address=\"${subnet}\"]] = 0) do={/ip dhcp-server network add address=${subnet} gateway=${gateway} dns-server=8.8.8.8,1.1.1.1}`,
    `:local notifyUrl \"${notifyUrl}\"`,
    `/tool fetch mode=https url=\$notifyUrl keep-result=no`,
    `/ip service disable api`,
    `/ip service disable ftp`,
    "# End of SmartLinkNet provisioning script",
  ].join("\r\n");
}

async function getServerEntry(): Promise<ServerEntry> {
  if (!serverEntryPromise) {
    serverEntryPromise = import("@tanstack/react-start/server-entry").then(
      (m) => (m.default ?? m) as ServerEntry,
    );
  }
  return serverEntryPromise;
}

// h3 swallows in-handler throws into a normal 500 Response with body
// {"unhandled":true,"message":"HTTPError"} — try/catch alone never fires for those.
async function normalizeCatastrophicSsrResponse(response: Response): Promise<Response> {
  if (response.status < 500) return response;
  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("application/json")) return response;

  const body = await response.clone().text();
  if (!body.includes('"unhandled":true') || !body.includes('"message":"HTTPError"')) {
    return response;
  }

  console.error(consumeLastCapturedError() ?? new Error(`h3 swallowed SSR error: ${body}`));
  return new Response(renderErrorPage(), {
    status: 500,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

export default {
  async fetch(request: Request, env: unknown, ctx: unknown) {
    try {
      const url = new URL(request.url);
      if (url.pathname.startsWith("/provision/notify/")) {
        const slug = url.pathname.replace("/provision/notify/", "").replace(/\/+$/, "");
        await markRouterOnline(slug, request);
        return new Response("ok", {
          status: 200,
          headers: { "content-type": "text/plain; charset=utf-8" },
        });
      }

      if (url.pathname.startsWith("/provision/")) {
        const slug = url.pathname.replace("/provision/", "").replace(/\/+$/, "");
        const body = await buildProvisionScript(slug, url.origin);
        return new Response(body, {
          status: 200,
          headers: {
            "content-type": "text/plain; charset=utf-8",
            "cache-control": "no-store",
          },
        });
      }

      const handler = await getServerEntry();
      const response = await handler.fetch(request, env, ctx);
      return await normalizeCatastrophicSsrResponse(response);
    } catch (error) {
      console.error(error);
      return new Response(renderErrorPage(), {
        status: 500,
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
  },
};
