import "./lib/error-capture";

import { consumeLastCapturedError } from "./lib/error-capture";
import { renderErrorPage } from "./lib/error-page";

type ServerEntry = {
  fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> | Response;
};

let serverEntryPromise: Promise<ServerEntry> | undefined;

function buildProvisionScript(slug: string) {
  const safeSlug = slug.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/(^-|-$)/g, "") || "smartlinknet";
  const identity = safeSlug.split("-").filter(Boolean).pop() || "MikroTik";
  const bridgeName = "smartlinknet-automatic";

  return [
    "# Generated by SmartLinkNet",
    `# Router identity: ${identity}`,
    `/system identity set name=\"${identity}\"`,
    `/interface bridge add name=${bridgeName} comment=\"SmartLinkNet auto-provisioned\"`,
    `/interface bridge port add bridge=${bridgeName} interface=ether2`,
    `/ip address add address=172.31.0.1/16 interface=${bridgeName} comment=\"SmartLinkNet default subnet\"`,
    `/ip pool add name=${bridgeName} ranges=172.31.0.2-172.31.0.254`,
    `/ip dhcp-server add name=${bridgeName} interface=${bridgeName} address-pool=${bridgeName} lease-time=12h`,
    `/ip dhcp-server network add address=172.31.0.0/16 gateway=172.31.0.1 dns-server=8.8.8.8,1.1.1.1`,
    `/ip service disable api`,
    `/ip service disable ftp`,
    "# End of SmartLinkNet provisioning script",
  ].join("\r\n");
}

async function getServerEntry(): Promise<ServerEntry> {
  if (!serverEntryPromise) {
    serverEntryPromise = import("@tanstack/react-start/server-entry").then(
      (m) => (m.default ?? m) as ServerEntry,
    );
  }
  return serverEntryPromise;
}

// h3 swallows in-handler throws into a normal 500 Response with body
// {"unhandled":true,"message":"HTTPError"} — try/catch alone never fires for those.
async function normalizeCatastrophicSsrResponse(response: Response): Promise<Response> {
  if (response.status < 500) return response;
  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("application/json")) return response;

  const body = await response.clone().text();
  if (!body.includes('"unhandled":true') || !body.includes('"message":"HTTPError"')) {
    return response;
  }

  console.error(consumeLastCapturedError() ?? new Error(`h3 swallowed SSR error: ${body}`));
  return new Response(renderErrorPage(), {
    status: 500,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

export default {
  async fetch(request: Request, env: unknown, ctx: unknown) {
    try {
      const url = new URL(request.url);
      if (url.pathname.startsWith("/provision/")) {
        const slug = url.pathname.replace("/provision/", "").replace(/\/+$/, "");
        const body = buildProvisionScript(slug);
        return new Response(body, {
          status: 200,
          headers: {
            "content-type": "text/plain; charset=utf-8",
            "cache-control": "no-store",
          },
        });
      }

      const handler = await getServerEntry();
      const response = await handler.fetch(request, env, ctx);
      return await normalizeCatastrophicSsrResponse(response);
    } catch (error) {
      console.error(error);
      return new Response(renderErrorPage(), {
        status: 500,
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
  },
};
