ALTER TABLE public.tenant_branding
ADD COLUMN IF NOT EXISTS success_color TEXT DEFAULT '#22C55E',
ADD COLUMN IF NOT EXISTS warning_color TEXT DEFAULT '#F59E0B',
ADD COLUMN IF NOT EXISTS error_color TEXT DEFAULT '#EF4444',
ADD COLUMN IF NOT EXISTS portal_bg_color TEXT,
ADD COLUMN IF NOT EXISTS portal_text_color TEXT,
ADD COLUMN IF NOT EXISTS email_from_name TEXT,
ADD COLUMN IF NOT EXISTS email_from_address TEXT,
ADD COLUMN IF NOT EXISTS brand_config JSONB DEFAULT '{}'::jsonb;
