// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Extended type that merges the generated types with all runtime tables from migrations
type AnyRecord = { [key: string]: any };

type ExtendedDatabase = Database & {
  public: Database['public'] & {
    Tables: Database['public']['Tables'] & {
      packages: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      customers: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      customer_documents: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      customer_notes: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      routers: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      router_backups: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      subscriptions: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      vouchers: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      wallets: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      wallet_transactions: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      invoices: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      invoice_items: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      payments: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      mpesa_callbacks: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      radius_users: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      network_adapters: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      ip_pools: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      wan_links: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      voucher_batches: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      wallets: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      wallet_transactions: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      invoices: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      invoice_items: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      payments: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      mpesa_callbacks: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      voucher_batches: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      vouchers: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      sessions: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      expenses: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      inventory: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      tickets: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      ticket_messages: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      installations: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      notifications: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      sms_logs: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
      settings: { Row: AnyRecord; Insert: AnyRecord; Update: AnyRecord; Relationships: [] };
    };
  };
};

function createSupabaseClient() {
  const isServer = typeof window === 'undefined';

  const SUPABASE_URL = isServer
    ? process.env.SUPABASE_URL
    : (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL);
  const SUPABASE_ANON_KEY = isServer
    ? process.env.SUPABASE_ANON_KEY
    : (import.meta.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY);

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_ANON_KEY ? ['SUPABASE_ANON_KEY'] : []),
    ];
    throw new Error(`Missing Supabase environment variable(s): ${missing.join(', ')}`);
  }

  return createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: isServer ? undefined : localStorage,
      persistSession: !isServer,
      autoRefreshToken: !isServer,
    }
  });
}

// Use separate instances for server and client to avoid stale closures
const _instances: { server?: ReturnType<typeof createSupabaseClient>; client?: ReturnType<typeof createSupabaseClient> } = {};

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    const key = typeof window === 'undefined' ? 'server' : 'client';
    if (!_instances[key]) _instances[key] = createSupabaseClient();
    return Reflect.get(_instances[key]!, prop, receiver);
  },
});

